"""Initial migration

Revision ID: 8ca4b3756b7e
Revises: 
Create Date: 2025-03-29 13:01:19.394165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca4b3756b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_tds_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loading_tds_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('loading_tds_percent')
        batch_op.drop_column('transport_tds_percent')

    # ### end Alembic commands ###
